name: murottal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  audio_video_progress_bar: ^0.11.0
  audioplayers: ^3.0.1
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.1.3
  get: 4.6.5
  speech_to_text: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/surah.json
